(ns cbt.core
  (:require [cbt.3-1])
  (:require [cbt.3-2])
  (:require [cbt.3-3])
  (:require [cbt.3-4])
  (:require [cbt.3-5])
  (:require [cbt.3-6])
  (:require [cbt.4-1])
  (:require [cbt.4-2])
  (:require [cbt.4-3])
  (:require [cbt.4-4])
  (:require [cbt.5-1])
  (:require [cbt.5-2])
  (:require [cbt.5-3])
  (:require [cbt.5-4])
  (:require [cbt.5-5])
  (:require [cbt.7-1])
  (:require [cbt.7-2])
  (:require [cbt.8-1])
  (:require [cbt.8-2])
  (:gen-class))

(defn -main
  [& args]
  (println "Hello, world!"))
